<a href="https://colab.research.google.com/github/RushanArshad/FCC-Python-Data-Analysis/blob/main/FCC_Challenges.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import matplotlib.pyplot as plt 

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)
print(certificates_earned[certificates_earned > 5])

Tom     8
Beau    6
dtype: int64


In [3]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})

certificates_earned.index = ['Tom', 'Kris', 'Ahmad', 'Beau']

print(certificates_earned.iloc[2])

Certificates        5
Time (in months)    9
Name: Ahmad, dtype: int64


Pandas Conditional Selectio nand Modifying DataFrames

In [4]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})
names = ['Tom', 'Kris', 'Ahmad', 'Beau']

certificates_earned.index = names
longest_streak = pd.Series([13, 11, 9, 7], index=names)
certificates_earned['Longest streak'] = longest_streak

print(certificates_earned)

       Certificates  Time (in months)  Longest streak
Tom               8                16              13
Kris              2                 5              11
Ahmad             5                 9               9
Beau              6                12               7


Pandas Creating Columns

In [9]:
certificates_earned['Certificates per month'] = round(
    certificates_earned['Certificates'] /
    certificates_earned['Time (in months)'], 2
)
print(certificates_earned)

       Certificates  Time (in months)  Longest streak  Certificates per month
Tom               8                16              13                    0.50
Kris              2                 5              11                    0.40
Ahmad             5                 9               9                    0.56
Beau              6                12               7                    0.50


Data Cleaning Introduction

In [10]:
import pandas as pd
import numpy as np

s = pd.Series(['a', 3, np.nan, 1, np.nan])

print(s.notnull().sum())

3


**Data Cleaning with DataFrames**

In [11]:
import pandas as pd
import numpy as np

s = pd.Series([np.nan, 1, 2, np.nan, 3])
s = s.fillna(method='ffill')

print(s)

0    NaN
1    1.0
2    2.0
3    2.0
4    3.0
dtype: float64


**Data Cleaning Duplicates** Consider the following dataset for ramen rating: 

In [12]:
df = pd.DataFrame({
...     'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
...     'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
...     'rating': [4, 4, 3.5, 15, 5]
... })
>>> df

brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

Now, lets see what happens when we use duplicated method on it

In [13]:
df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

**Reading Data Introduction**

In [18]:
import csv

with open(certificates.csv, 'r') as fp:
    reader = csv.reader(fp, delimiter=$)
    next(reader)
    for index, values in enumerate(reader):
        name, certs_num, months_num = values
        print(f"{name} earned {certs_num} certificates in {months_num} months")


SyntaxError: ignored

**Reading Data CSV and TXT**

How would you import the CSV file data.csv and store it in a DataFrame using the Pandas module?


import pandas as pd
df = pd.csv("data.csv")

import pandas as pd
df = pd.read_csv("data.csv") **CORRECT**

import pandas as pd
pd.read_csv("data.csv")

import pandas as pd
df = pd.csv_reader("data.csv")

**Reading Data from Databases**

What method does a Cursor instance have and what does it allow?


The Cursor instance has a .run() method which allows you to run SQL queries.

The Cursor instance has a .select() method which allows you to select records.

The Cursor instance has an .execute() method which will receive SQL parameters to run against the database. **CORRECT**

**Parsing HTML and Saving Data**

What Python library has the .read_html() method we can we use for parsing HTML documents and extracting tables?


BeautifierSoupy

WebReader

HTTP-master

Pandas.  **CORRECT**


**Introduction to Numpy**

Why are Numpy arrays faster than regular Python lists?


Numpy does not perform type checking while iterating through objects.

Numpy uses fixed types.

Numpy uses contiguous memory.

All of the above.  **CORRECT**


**Basics of Numpy**

In [19]:
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


**Numpy - Accessing and Changing Elements, Rows, Columns**

In [22]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

a[:, 2] = 20

print(a)

# Output:
# [[ 1  2  20  4  5]
# [ 6  7 20  9 10]]

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]


**Numpy - Initializing Different Arrays**

In [23]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


**Numpy - Initialize Array Problem**

In [26]:
output = np.zeros((7,7))

z = np.ones((5, 5))
z[2, 2] = 5

output[1:-1, 1:-1] = z

print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**Copying Arrays Warning**

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20

**Numpy - Mathematics**

Numpy max function along with sum function adds max values from both rows and returns a scalar.

In [27]:
import numpy as np

a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()

print(b)

15


**Numpy - Reorganizing Arrays**

In [28]:
a = np.ones((2, 4))
b = a.reshape((4, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
